apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - flux-system
  - apps
  - monitoring

# maybe namespace layering later? i don't know, I'm tired boss
# - namespaces
# - apps/ns1
# - apps/ns2
