paperlessngx:
  image:
    repository: ghcr.io/paperless-ngx/paperless-ngx
    pullPolicy: IfNotPresent

  env:
    - name: PAPERLESS_URL
      value: "https://paperless.shakir.cloud"
    - name: PAPERLESS_TIME_ZONE
      value: "America/Los_Angeles"
    - name: PAPERLESS_OCR_LANGUAGE
      value: "eng"
    - name: "PAPERLESS_OCR_LANGUAGES"
      value: "ara"
    - name: PAPERLESS_FILENAME_FORMAT
      value: "{{ correspondent }}/{{ created_year }}-{{ created_month }}-{{ title }}"
    - name: PAPERLESS_CONSUMER_POLLING
      value: "30"

adminSecret:
  enabled: true
  create: true
  name: paperless-ngx-admin
  usernameKey: username
  passwordKey: password
  username: admin
  password: changeme

redis:
  image:
    repository: docker.io/library/redis
    pullPolicy: IfNotPresent

persistence:
  shared:
    existingClaim: paperless-ngx-data


