resources:
  - release.yaml

configMapGenerator:
  - name: paperless-app-values
    files:
      - app-values.yaml=app-values.yaml
  - name: paperless-data-values
    files:
      - data-values.yaml=data-values.yaml

generatorOptions:
  disableNameSuffixHash: true
