resources:
  - release.yaml

configMapGenerator:
  - name: wordpress-values
    files:
      - wp-values.yaml=wp-values.yaml
  - name: wordpress-data
    files:
      - wp-data-values.yaml=wp-data-values.yaml

generatorOptions:
  disableNameSuffixHash: true
