app:
  name: bentopdf
  image:
    repository: bentopdf/bentopdf
    tag: latest
    pullPolicy: IfNotPresent

# workaround to avoid a bug in the chart
  volumeMounts:
    - mountPath: ""
      subPath: ""

  replicaCount: 1

  containerPort: 3000

  service:
    port: 80
    targetPort: 80

ingress:
  enabled: true
  host: bentopdf.shakir.cloud
  ingressClassName: nginx
