app:
  name: bentopdf
  image:
    repository: bentopdf/bentopdf
    tag: latest
    pullPolicy: IfNotPresent

  replicaCount: 1

  containerPort: 80

  service:
    port: 80
    targetPort: 80

ingress:
  enabled: true
  host: bentopdf.shakir.cloud
  ingressClassName: nginx
