apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - release.yaml

configMapGenerator:
  - name: excalidraw-values
    files:
      - values.yaml=excalidraw-values.yaml

generatorOptions:
  disableNameSuffixHash: true
