app:
  name: deemix
  image:
    repository: ghcr.io/bambanah/deemix
    tag: latest
    pullPolicy: IfNotPresent

  replicaCount: 1

  service:
    port: 80
    targetPort: 6595

  volumeMounts:
    - mountPath: /downloads
      subPath: downloads
    - mountPath: /config
      subPath: config

  env:
    - name: PUID
      value: "1000"
    - name: PGID
      value: "1000"
    - name: UMASK_SET
      value: "022"
    - name: DEEMIX_SINGLE_USER
      value: "true"

ingress:
  enabled: true
  host: deemix.shakir.cloud
  ingressClassName: nginx

persistence:
  enabled: true
  size: 200Mi
  accessMode: ReadWriteMany
  reclaimPolicy: Retain
  nfs:
    server: synology.shakir.cloud
    path: /volume1/k3s-main/deemix
