app:
  name: excalidraw
  image:
    repository: excalidraw/excalidraw
    tag: latest
    pullPolicy: IfNotPresent

# workaround to avoid a bug in the chart
  volumeMounts:
    - mountPath: ""
      subPath: ""

  replicaCount: 1

  containerPort: 80

  service:
    port: 80
    targetPort: 80

ingress:
  enabled: true
  host: draw.shakir.cloud
  ingressClassName: nginx
