labels:
  app: paperless-ngx
annotations:
  volume.kubernetes.io/description: "Shared PVC for paperless-ngx"
  custom.synology/path-hint: "maps to /vol1/k3s-main/paperless-ngx"

persistence:
  name: paperless-ngx-data
  size: 100Mi
  accessMode: ReadWriteMany
  reclaimPolicy: Retain
  nfs:
    server: synology.shakir.cloud
    path: /volume1/k3s-main/paperless-ngx
