apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: shared-sources
  namespace: flux-system
spec:
  interval: 5m
  path: ./clusters/dev/flux-system/shared-sources
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
