# Common HelmRelease values
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apps

resources:
  - release-excalidraw.yaml
  - release-metube.yaml
  - release-omni-tools.yaml
  - release-deemix.yaml
  - release-spdf.yaml

patches:
  - target:
      kind: HelmRelease
    path: common-patch.yaml
