# Common HelmRelease values
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apps

resources:
  - actualbudget/
  - deemix/
  - excalidraw/
  - gaseous/
  - homepage/
  - jellyfin/
  - metube/
  - omni-tools/
  - spdf/
  - speedtest/
  # - release-jellyfin.yaml
  # - release-jellyfin-config.yaml
  # - release-jellyfin-media.yaml
  # - release-paperless-ngx.yaml
  # - release-paperless-ngx-data.yaml
  # - release-karakeep.yaml

patches:
  - target:
      kind: HelmRelease
    path: common-patch.yaml
