# Common HelmRelease values
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apps

resources:
  - release-excalidraw.yaml
  - release-metube.yaml
  - release-omni-tools.yaml
  - release-deemix.yaml
  - release-spdf.yaml
  - release-gaseous.yaml
  - release-speedtest.yaml
  - release-jellyfin.yaml
  - release-jellyfin-config.yaml
  - release-jellyfin-media.yaml
  - release-actualbudget.yaml
  - release-homepage.yaml
  - release-paperless-ngx.yaml
  - release-paperless-ngx-data.yaml
  - release-karakeep.yaml

patches:
  - target:
      kind: HelmRelease
    path: common-patch.yaml
