# Common HelmRelease values
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apps

resources:
  - actualbudget/
  - bentopdf/
  - carlogger/
  - deemix/
  - excalidraw/
  - gaseous/
  - homepage/
  - jellyfin/
  - metube/
  - omni-tools/
  - paperless-ngx/
  - speedtest/
  # - release-paperless-ngx-data.yaml
  # - release-karakeep.yaml

patches:
  - target:
      kind: HelmRelease
    path: common-patch.yaml
