apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin-config
  namespace: default

spec:
  interval: 5m
  releaseName: jellyfin-config

  chart:
    spec:
      chart: nfspersistence
      version: "0.3.1"
      sourceRef:
        kind: HelmRepository
        name: tinycloud-labs
        namespace: flux-system
      interval: 1m

  values:
    labels:
      app: jellyfin
    annotations:
      volume.kubernetes.io/description: "Shared PVC for jellyfin-config"
      custom.synology/path-hint: "maps to /vol1/k3s-main/jellyfin-config"

    persistence:
      name: jellyfin-config
      size: 100Mi
      accessMode: ReadWriteMany
      reclaimPolicy: Retain
      nfs:
        server: synology.shakir.cloud
        path: /volume1/k3s-main/pv-jellyfin-config
