name: 'Kustomize Build'
on:
  pull_request:
    paths:
      - 'clusters/prod/**'
      - 'clusters/dev/**'
  workflow_dispatch:

jobs:
  kustomize:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cluster:
          - path: clusters/prod
            name: prod
          - path: clusters/dev
            name: dev
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref }}

      - name: 'Kustomize Build'
        uses: karancode/kustomize-github-action@v1.3.2
        with:
          kustomize_version: '5.8.0'
          kustomize_build_dir: ${{ matrix.cluster.path }}
          kustomize_comment: true
          kustomize_output_file: "gitops/rendered.yaml"
          kustomize_build_options: "--load-restrictor=LoadRestrictionsNone"
          enable_alpha_plugins: false
          token: ${{ secrets.GITHUB_TOKEN }}
