apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: HelmRelease
      name: paperless-ngx
    path: patch.yaml
  - target:
      kind: HelmRelease
      name: paperless-ngx-data
    path: patch-data.yaml
