apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - release-prometheus-stack.yaml
  - release-loki-stack.yaml

patches:
  - target:
      kind: HelmRelease
    path: common-patch.yaml

secretGenerator:
  - name: grafana-admin
    namespace: monitoring
    literals:
      - admin-password={{randAlphaNum 32}}
    options:
      disableNameSuffixHash: true
